### recuperar todas la películas
GET http://localhost:3000/movies

### recuperar una película por id
GET http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

### recuperar todas la películas por genero
GEt http://localhost:3000/movies?genre=Action

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Hii FI",
  "year": 1999,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": [
    "Action",
    "Crime",
    "Drama"
  ],
  "rate": 9
}

### Actualizar una película
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: "application/json"

{
  "title": "Hola",
  "year": "1995"
}

### abds